version: '3'
services:
  calculator:
    image: edyta/calculator
    build: .
    container_name: mycontainer
    ports:
      - "8080:8080"
    volumes:
      - ./var/log/calculator:/var/log/calculator

    logging:
      driver: json-file

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
        - "3000:3000"
