version: '3'
services:
  calculator:
    image: edyta/calculator
    build: .
    container_name: mycontainer
    ports:
      - "8080:8080"
    volumes:
      - my-vol:/var/lib/docker/volumes/my-vol/_data
    logging:
      driver: json-file
volumes:
  my-vol:
    external: true